---
name: "Fing Agent"
version: "0.0.1"
slug: fing_agent
description: "Run Fing Agent inside Home Assistant OS as an add-on."
url: http://github.com/mirarus/ha-fing-agent
arch:
  - amd64
  - aarch64
startup: services
boot: auto
hassio_api: true
hassio_role: manager
homeassistant_api: false
panel_icon: "mdi:lan"
host_network: true
privileged:
  - NET_ADMIN
map:
  - config:rw
  - share:rw
options:
  api_key: ""
schema:
  api_key: str
environment:
  API_KEY: "{api_key}"