name: "Fing Agent"
version: "1.1.1"
slug: "fing-agent"
description: "Run Fing Agent inside Home Assistant OS as an app"
url: "https://github.com/serverwentdown/ha-fing-agent"
arch:
  - amd64
  - aarch64
startup: services
boot: auto
host_network: true
privileged:
  - NET_ADMIN
ports:
  44444/tcp: 44444
ports_description:
  44444/tcp: "UPnP publisher"
map:
  - type: data
    path: /app/fingdata
image: "fing/fing-agent"
options: {}
schema: {}
