---
name: "Fing Agent"
version: "0.0.1"
slug: "fing-agent"
description: "Run Fing Agent inside Home Assistant OS as an add-on."
url: "https://github.com/mirarus/ha-fing-agent"
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
startup: services
boot: auto
host_network: true
privileged:
  - NET_ADMIN
ports:
  - 44444/tcp
image: "fing/fing-agent:latest"
map:
  - config:rw
  - share:rw
options: {}
schema: {}